//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinitySettingsCreater.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfinitySettingsCreater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10021 CPc14XqVn7Jv
        ///10022 b5bc4ssnF79r
        ///10041 CM7z4MXWd7dg
        ///10042 sHCR4xhw77pn
        ///10051 b9Th4cHJq7JM
        ///10052 MR7x4V79h7zf
        ///10061 CqVH4Wfsn74X
        ///10062 7Hqc4KNFV7fp
        ///10081 nnfd4K9RJ7Tf
        ///10082 J3F74RFtw7wR
        ///10091 vvWp4mtvd7gv
        ///10092 vv7T4cNnz7hV
        ///10101 fRmd4kfCR7bq
        ///10102 f9kv4Vjjc7dT
        ///10131 rKkP4nR4W7cF
        ///10132 7Pdb4Pqnm7dR
        ///10161 kWxK4k7cs7j3
        ///10162 xVc34C3MJ7RT
        ///10171 w7jM4Czws7Cv
        ///10172 HNwg4cvjH7nL
        ///10191 wWpv4Vs9d7q9
        ///10192 xCJ34Nx447Jd
        ///10201 cmVW47JRp7rM
        ///10202 4qkw4HbxV73k
        ///10211 gNdV4Wgm97WC
        ///10212 LbJw4p47x73M
        ///10231 9kKw4hFCM7mL [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string arraySipPass {
            get {
                return ResourceManager.GetString("arraySipPass", resourceCulture);
            }
        }
    }
}
